### PR TITLE
Mark useTextField's  parameter as optional

### PR DESCRIPTION
**Pull request by Andarist**
The only thing that it is used for is `useFocusable` and as `ref` is optional for `useFocusable` itself:
https://github.com/adobe-private/react-spectrum-v3/blob/4c53104f80ba25c112bb27ed3591b5d0e0c26a24/packages/%40react-aria/focus/src/useFocusable.ts#L22
then I would say that this should be optional for `useTextField` as well. One might not want to use `autoFocus` at all so requiring a ref just for not used feature seems like overkill.

### CODE REVIEW

**Comment by devongovett** [comment]
Not sure about this. Is it weird to have a prop in the API that doesn't work if you don't pass a ref? There's no warning or error if you don't pass it and use the `autoFocus` prop, so it may be hard for people to know if they've introduced a bug. Currently, everything that uses `useFocusable` does require its ref, so maybe the solution here is to also require it in `useFocusable`?

**Comment by Andarist** [comment]
For example `useTextField` more often than not will be used with native input elements that support native `autoFocus` prop, so having to pass a ref to achieve the same seems to me like overkill.

I recognize the DX problem you have mentioned - one solution for this would be to check in an effect if an element has received focus natively and warn if it has not. This might require some code changes though as `useFocusable` would have to gain knowledge about `id`.

**Comment by devongovett** [comment]
Ah. I think the reason we implemented `autoFocus` ourselves rather than relying on the native prop was that the native prop caused issues in dialogs since the focusing happened before any `useLayoutEffect`s fired.` FocusScope` (as used in dialogs) uses a layout effect to record the focused element before the dialog opens. But the `autoFocus` prop causes the focus to happen before the layout effect has a chance to run. Instead, we implemented autoFocus for textfield in a separate effect to ensure that it runs after the dialog opens. Not great but it works. If you have a better suggestion for that I'd love to hear it.

**Comment by Andarist** [comment]
Ok, so given the chosen API and the implementation for FocusScope it makes sense to do this through a custom logic for autoFocusing at all times. However, it also means that there is a coupling between those 2 (FocusScope + useTextField), whereas everything is split into separate packages so they can be cherry-picked based on needs. Of course, one benefits most from the React Aria project by using its hooks for all the things, but when gradually migrating or just wanting to use a single thing then this whole thing might not work as expected.

I recognize the problem though, thought about it right now a little bit (and I bet you have thought about it more extensively) and I don't have a good alternative. Looking at React's FocusScope experiment they haven't solved it either as the `nodeToRestore` was recorded in `onMount`:
https://github.com/facebook/react/blob/db3ae32b8fe2c3fe24c4f5496aecdeab24b9d719/packages/react-events/src/dom/FocusScope.js#L146 .

As this is `FocusScope` requirement (to avoid using native `autoFocus`) one thing that could be done would be validating in DEV if the recorded `document.activeElement` is within scope. From what I understand it never should be because that would make `restoreFocus` unusable. This could, of course, give hints about how the problem can be fixed. This would decrease the coupling between `FocusScope` and `useTextField` in my opinion.

Going back to the original discussion though 😅 I see how the ref is required when using `autoFocus` prop - you don't want to return native `autoFocus` to the caller as that would conflict with other hooks in the family, so I'm OK with that, changing this would be asking for too much. However, you could make `ref` optional and introduce a DEV warning for `autoFocus === true && ref === undefined` case. It's up to you - I think you should do either this or if you don't agree with this approach then make `ref` required for `useFocusable` as well like you have proposed before.

**Comment by devongovett** [comment]
> but when gradually migrating or just wanting to use a single thing then this whole thing might not work as expected.

yeah.

> one thing that could be done would be validating in DEV if the recorded document.activeElement is within scope

That's a good idea.

> However, you could make ref optional and introduce a DEV warning for autoFocus === true && ref === undefined case

That's a possibility, but I don't see it as terribly inconvenient to pass a ref. I think I'd rather make the ref required in `useFocusable`.

**Pull request closed without merging**
