### PR TITLE
RSP-1834 [Accessibility][Docs] Popup links are not keyboard accessible in Firefox

### PR DESCRIPTION
**Pull request by majornista**
Popup links have a valid href, so usePress is not interpreting them as links that React-Spectrum should handle with the Enter key, even though the default behavior has been prevented with event.preventDefault in an onClick handler.

See: https://github.com/adobe-private/react-spectrum-v3/blob/master/packages/%40react-aria/interactions/src/usePress.ts#L573-L577

One solution is to remove href and set role="link" and tabIndex="0". We also have to make sure that links within the Popup still work.  

This may be another use case we need to account for in usePress.

Closes https://jira.corp.adobe.com/browse/RSP-1834

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [Issue RSP-1834](https://jira.corp.adobe.com/browse/RSP-1834).
- Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Open documentation site in Firefox
2. Open a page with popup links like /react-aria/useListBox.html
3. Tab to one of the popup links like "AriaListBoxOptions"
4. Press Enter key to expand the Popover
5. Press Tab key to navigate to a link within the Popover, like "CollectionChildren"
6. Press Enter key to update the breadcrumb location within the Popover
7. Focus will get set to the h3 element for the current breadcrumb location in the Popover

* Note a separate issue:  when there are enough breadcrumb items for the Breadcrumbs to collapse, the Breadcrumb MenuTrigger fails to open the menu within the Popover.

## 🧢 Your Project:

Accessibility

### CODE REVIEW

**Comment by snowystinger** [comment]
is this right? i thought the last breadcrumb shouldn't ever get focus? And it probably shouldn't have a link underline and turn the cursor style to the little hand?
Screen Shot 2020-06-26 at 10 05 06 AM

**Comment by majornista** [comment]
My intent here is for focus to not get lost to the `document.body` when the popover content changes, removing the link that was clicked. Setting focus to the current location seemed to make the most sense.

The earlier implementation had this last item as an h3, and I didn't think of it as that odd for a static heading to receive focus temporarily, when popover contents are refreshed. 

We could update CSS to ignore `[aria-disabled=true]`  when determining whether to display the `:focus-ring` or `:hover` styles.

**Comment by devongovett** [comment]
I separated out just the part that fixes the enter key to open a popover in #726. I think we'd like to test the changes for breadcrumbs more carefully (esp CSS changes) when we're less close to a release.

**Comment by majornista** [comment]
@devongovett, @dannify I'm ok to close this PR, now that #726 has been merged. I have opened #728 to manage focus when setBreadcrumbs replaces the content of the documentation popover.

**Pull request closed without merging**
