### PR TITLE
Remove pointer cursor from non-link elements

### PR DESCRIPTION
**Pull request by devongovett**
Following the new [Spectrum cursor guidelines](https://spectrum-contributions.corp.adobe.com/page/cursor-guidelines-beta/), this removes the pointer (hand) cursor from most clickable elements, except navigational elements like links, and uses the default arrow cursor instead. This may be controversial on the web where the pointer cursor is often misused, but better aligns with native elements, the CSS spec, both Microsoft and Apple's human interface guidelines, browser native `<button>`, checkboxes, radios, etc.

The remaining components that use the pointer cursor are:

* link
* breadcrumbs
* sidenav
* steplist (not completely sure about this one, but seems "navigational" to me)

### CODE REVIEW

**Comment by devongovett** [comment]
Some additional resources for people to read about this:

* https://adamsilver.io/articles/buttons-shouldnt-have-a-hand-cursor/
* https://adamsilver.io/articles/buttons-shouldnt-have-a-hand-cursor-part-2/
* https://www.w3.org/TR/CSS2/ui.html#propdef-cursor

**Comment by devongovett** [comment]
Yeah that's a good one. Feels like an issue regardless of the cursor though. e.g. on mobile, there is no cursor anyway.

**Comment by cheapsteak** [comment]
A thought - 

In desktop apps, nearly everything we can see is clickable, when there's both interactive and non-interactive elements, the interactive elements are almost always in their own section, separate from non-interactive elements (taskbar, toolbar), it tends to be fairly obvious what's what; there's a clearly separate "content" section




In browsers / web-apps, non-interactive elements (i.e. "content" and "data") is more numerous, and interactive/non-interactive elements tend to more closely mixed together

e.g..
image

A lot of these "things that need to be clickable aren't", at a glance, aren't immediately obvious that they're clickable  
Some of the things that aren't clickable (e.g. the collaborator badge) aren't obviously unclickable

`cursor: pointer` is useful for helping make the intractability of these not-buttons more quickly evident when hovering over them; If we accept that these clickable not-buttons need `cursor: pointer`, then it feels rather jarring for actual buttons not to have cursor: pointer.  imo "pointer - can click/ no-pointer - can't click" becomes a language we code-switch into when we're in a browser



A possibly interesting .. case study? (might be a bit of a stretch to call it that, lol) of "the same app" in two different contexts
outlook.com (left, cursor pointer) and windows 10 mail (right, normal arrow pointer)

**Comment by cheapsteak** [comment]
(maybe a prop on Provider so we can specify whether buttons should have cursor pointer? :P)

**Comment by devongovett** [comment]
This was a decision made by the Spectrum design team. See the comment above for some resources about why the decision was made. Basically, the pointer cursor is reserved for links, and the arrow cursor is used on all other elements. The cursor is less important these days due to touch anyway, so it's better to make it clear what elements are clickable without relying on the cursor to indicate it.

**Pull request merged**
